### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion.stanford.edu#17]
We should be able to add the new Legion logo as the favicon using jeykll. I haven't figured out how to do this yet, but a few tutorials seem to suggest it should be easy...

**Comment by elliottslaughter** [comment]
It's mostly a matter of creating images of the appropriate sizes.

According to [this website](https://mobiforge.com/design-development/adding-favicons-in-a-multi-browser-multi-platform-world) we want the following sizes:

    48×48
    96×96
    144×144
    192×192
    256×256
    384×384
    512×512

And then if you care about Apple devices, add:

    120×120: iPhone
    152×152: iPad
    167×167: iPad Retina
    180×180: iPhone Retina

All of this can be PNG, don't bother with the obsolete ICO format.

If you get me the files, I can put them on the website.

**Comment by lightsighter** [comment]
Let's see if I can them all in this tar file.
[favicon.tar.gz](https://github.com/StanfordLegion/legion.stanford.edu/files/10454176/favicon.tar.gz)

**Comment by elliottslaughter** [comment]
Should be up now.

**Comment by lightsighter** [comment]
Confirmed!
