### ISSUE TITLE
Realm Machine Model documentation has processor kind swapped for CPU and GPU

### ISSUE THREAD

**Issue by reazulhoque** [StanfordLegion/legion.stanford.edu#21]
For different Realm processor kind documentation (https://legion.stanford.edu/tutorial/realm/machine_model.html#processor), we have `TOC_PROC` represented as CPU and `LOC_PROC` represented as GPU. They are swapped and should be corrected.

**Comment by eddy16112** [comment]
Thanks! I have created a PR to fix it https://github.com/StanfordLegion/legion.stanford.edu/pull/22
